author: Andy # 作者
description: Andy's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: 阅读全文

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

baidu_id:

about: 
  banner: https://i.imgur.com/YT9F84p.jpg
  avatar: https://i.imgur.com/MytU5HF.png
  description: 雅致寓于高阁渔舟唱晚，古典悠然；格调外发园林绿树萦绕，馥郁清香。